carousel + gallery feature (#81)
PACS-TMU/usstm-website pull request #96
Opened 2024-02-16 18:06 UTC by andrearcaina

- utilized `react-slick` package for carousel
- tried doing a masonry gallery, but it was too hard
    - might use react-masonry or something
- created data with placeholder text, year, and images for both carousel and gallery in `public/data`

2024-02-17 20:08 UTC, williamKhine requested changes
The carousel component has an overflow-x issue caused by the arrows.

Affected: Laptops, Phones

To reproduce, go to the yearbook page and try scrolling sideways. Compare to other pages which does not have an overflow issue.

2024-02-17 20:25 UTC, MoNakouzi requested changes
We are already using a carousel library called Swiper JS, see `/about/your-team` to see an example.  Please replace `react-slick` with the Swiper JS implementation.

2024-02-17 20:26 UTC, andrearcaina commented
Will do @MoNakouzi! I'll replace the library with Swiper JS.

2024-02-21 20:11 UTC, MoNakouzi approved these changes

2024-02-21 20:25 UTC, williamKhine approved these changes

2024-02-21 20:30 UTC, merged